## What is Numpy ?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### To check the version of Numpy use the following command..

In [1]:
import numpy as np
print(np.__version__)

1.21.5


# 1. Creating Numpy array

np.array --> 0D,1D,2D,3D array can be created by using the np.array method

In [2]:
arr=np.array([1,2,3])

In [3]:
print(arr)

[1 2 3]


2D and 3D array

In [4]:
arr2=np.array([[10,20,30],[3,5,8]])

In [5]:
print(arr2)

[[10 20 30]
 [ 3  5  8]]


In [6]:
arr3=np.array([
    [[1,2,3],[4,5,6]],
    [[10,20,30],[40,50,60]],
    [[100,200,300],[400,500,600]]
])

In [7]:
print(arr3)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]


### To chek the type of array

In [8]:
print(type(arr2))

<class 'numpy.ndarray'>


### Array can be created of any dtype

In [9]:
a=np.array([2,4,6],dtype=float)

In [10]:
print(a)

[2. 4. 6.]


In [11]:
a=np.array([2,4,6],dtype=bool)

In [12]:
print(a)

[ True  True  True]


In [13]:
a=np.array([2,4,6],dtype=complex)

In [14]:
print(a)

[2.+0.j 4.+0.j 6.+0.j]


#### arange() function also creat array of element in the given range

In [15]:
c=np.arange(1,11)

In [16]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
b=np.arange(1,11,2)

In [18]:
print(b)

[1 3 5 7 9]


### reshape() method to convert in nd array

In [19]:
c.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
c.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### By using np.ones() method we can create the array with all element as 1

In [21]:
d=np.ones((3,4))

In [22]:
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### To create array of random element between 0 to 1 use np.random

First random is the class and 2nd random is the method used for creating array of random number

In [24]:
np.random.random((2,3))

array([[0.09562163, 0.95469436, 0.35541744],
       [0.31007891, 0.192903  , 0.46999619]])

### To create array at equal distance between given range use...

np.linspace()--> which is linear space takes three arguments
1. lower limit 
2. upper limit
3. Number of items

In [25]:
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

### To create identity matrix use ..

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 2. Array Attributes

### To check the dimesions of array use ndim (Number of dimensions)

In [27]:
arr2.ndim

2

In [28]:
a.ndim

1

### To check the shape of array i.e number of rows and columns use np.shape

In [29]:
arr2.shape

(2, 3)

In the below code if array is 3d then 1st parameter tells how many 2-d arrays are present and 2nd,3rd parameter tells number of rows and number of columns in each 2-d array

In [30]:
arr3.shape

(3, 2, 3)

### To check the size of array means number of element present 

In [31]:
arr3.size

18

### To check the memory size of each element in an array

In [32]:
arr2.itemsize

4

#### To check the data type of element present in an array

In [33]:
arr3.dtype

dtype('int32')

## Changing data type of an array which is already created

In [34]:
arr3.dtype

dtype('int32')

In [35]:
arr3.astype(np.bool)

C:\Users\abhin\AppData\Local\Temp\ipykernel_5872\4033585443.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr3.astype(np.bool)


array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

# 3. Array Operations

In [36]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [37]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 3.1 Scaler operation

In scaler operation we did any operation with a single value for eg. Multiplication with 2, division with 5, addition with 10 etc.. 1. Arithmetic operation(+,-,*,/,**) 2. Relational operation(>,<,>=,<=,==,!=)

In [39]:
a1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [40]:
a1/2,a1**2,a1+5,a1-3

(array([[0. , 0.5, 1. , 1.5],
        [2. , 2.5, 3. , 3.5],
        [4. , 4.5, 5. , 5.5]]),
 array([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]], dtype=int32),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[-3, -2, -1,  0],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]))

In [41]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

## 3.2 Vector operation

When we apply any operation on 2 np.array it is called vector operation

In [42]:
a1+a2,a1-a2,a1*a2,a1/a2

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 array([[-12, -12, -12, -12],
        [-12, -12, -12, -12],
        [-12, -12, -12, -12]]),
 array([[  0,  13,  28,  45],
        [ 64,  85, 108, 133],
        [160, 189, 220, 253]]),
 array([[0.        , 0.07692308, 0.14285714, 0.2       ],
        [0.25      , 0.29411765, 0.33333333, 0.36842105],
        [0.4       , 0.42857143, 0.45454545, 0.47826087]]))

# 4. Array functions

In [43]:
b1=np.random.random((3,3))
b1=np.round(b1*100)

In [44]:
b1.astype(np.int32)

array([[28, 28, 88],
       [ 2, 99, 71],
       [33, 68, 99]])

### 4.1 Algebraic function ( Max, Min, sum, prod)

Max returns maximum value present in array, Min returns minimum value present in array, sum returns sum of all element in array, prod return the product of all the element in array.
If you want the max/min/sum/prod of rows or columns then axis=1==> row and axis=0==> column

In [45]:
np.min(b1),np.max(b1),np.sum(b1),np.prod(b1)

(2.0, 99.0, 516.0, 215466779759616.0)

In [46]:
np.min(b1,axis=1)

array([28.,  2., 33.])

### 4.2 Statistical function (mean,median,mode,std,variance)

mean returns the 

In [47]:
np.mean(b1),np.median(b1),np.std(b1),np.var(b1)

(57.333333333333336, 68.0, 33.47967874530592, 1120.888888888889)

In [48]:
np.mean(b1,axis=1)

array([48.        , 57.33333333, 66.66666667])

### Dot product

Dot product (3,4).(4,3) multiplication is done row by column similar to the matrix in 12th class we have done

In [49]:
c1=np.arange(12).reshape(3,4)
c2=np.arange(12,24).reshape(4,3)
prod=np.dot(c1,c2)

In [50]:
print(prod)

[[114 120 126]
 [378 400 422]
 [642 680 718]]


### log, exp, round, floor, ceil 

In [51]:
np.log(c2),np.exp(a1)

(array([[2.48490665, 2.56494936, 2.63905733],
        [2.7080502 , 2.77258872, 2.83321334],
        [2.89037176, 2.94443898, 2.99573227],
        [3.04452244, 3.09104245, 3.13549422]]),
 array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
        [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]]))

In [52]:
np.round(np.random.random((3,4))*100)

array([[46., 48., 39., 39.],
       [70., 70.,  2.,  9.],
       [12., 21., 44., 49.]])

In [53]:
np.floor(np.random.random((3,4))*100)

array([[ 9., 72., 12., 56.],
       [11.,  2., 61., 70.],
       [34., 24., 22., 33.]])

In [54]:
np.ceil(np.random.random((3,4))*100)

array([[86., 33., 70., 53.],
       [14., 81., 54., 96.],
       [42.,  1., 19., 22.]])

# 5. Indexing and slicing

In [55]:
d1=np.arange(10)
d2=np.arange(12).reshape(3,4)
d3=np.arange(8).reshape(2,2,2)

In [56]:
d1,d2,d3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

Indexing start from 0 to n-1, for the first element it is 0 and for the last element it is -1.
index number should be written inside the square braces

In [57]:
d1[0],d1[-1]

(0, 9)

In [58]:
d2[0][1],d2[1,2]

(1, 6)

to find the element in 3-d array first we will pass the index of 2-d array then pass the row followed by column
d3[1,0,1]

In [59]:
d3[1,0,1]

5

In [60]:
d3[0,1,0]

2

In [61]:
d1[0:3],d1[3:7:2]

(array([0, 1, 2]), array([3, 5]))

In [62]:
d2[0,:]

array([0, 1, 2, 3])

In [63]:
d2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

Slicing is done by row and column [0:2,3:7], 0 to 2 row and columns from 3 to 7 

In [64]:
d2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [65]:
d2[1,::3]

array([4, 7])

In [66]:
d4=np.arange(27).reshape(3,3,3)

In [67]:
d4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Now we will do the slicing in the 3-d array. [starting index:ending index:jump(skip)]

In [68]:
d4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
d4[0,1,:]#slicing 1st 2-d array and 2nd row with all columns i.e 3,4,5

array([3, 4, 5])

To print 2nd 2-d arrays 2nd columns with all the rows

In [70]:
d4[1,:,1]

array([10, 13, 16])

To fetch 22,23,25,26 from the array we will do slicing

In [71]:
 d4[2,1:,1:]

array([[22, 23],
       [25, 26]])

To fetch 0,2,18,20 from the array

In [72]:
d4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### 5.1 Fancy indexing

In fancy indexing we pass the list and in the list we pass the row number as well as columns as per need.
for example. d2[[row numbers separated by commas 2,3,4],[columns number separated by commas]]

In [73]:
d=np.arange(24).reshape(6,4)

In [74]:
d[[1,3,5]]# To print the row number having index 1,3,5

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [75]:
d[:,[2,3]]# sare row and 2,3 columns as per indexing

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

### 5.2 Boolean indexing ==> means indexing based on condition 

Boolean indeximg means condition based fetching element from the array. for eg u have to find out those element who are the multiple of 5, or find out those element who are even/odd.

In [76]:
f=np.random.randint(1,100,24).reshape(6,4)

np.random.randint()==> produce the value between two value it took 3 argument 
1. lower range
2. higher range
3. Number of element in between range

In [77]:
f

array([[25, 54, 78, 87],
       [87, 95, 24, 81],
       [69, 61,  4, 61],
       [87,  7, 42, 37],
       [55, 35, 81, 78],
       [25, 29, 21, 54]])

Q.1 Find all the elements greater than 60
Q.2 Find all the elements greater than 50 and even
Q.3 Find the even element 

In [78]:
f>60

array([[False, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [79]:
f[f>60]

array([78, 87, 87, 95, 81, 69, 61, 61, 87, 81, 78])

In [80]:
f%2==0

array([[False,  True,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False, False,  True]])

In [81]:
f[f%2==0]

array([54, 78, 24,  4, 42, 78, 54])

In [82]:
f[(f>60)&(f%2==0)]

array([78, 78])

# 6. Iterating

In [83]:
for i in d1:
    print(i)

0
1
2
3
4
5
6
7
8
9


np.nditer(array)==> it will convert in 1-d array of those array who is already in higher dimensions like 3-d,2-d, and from there you can access the element easily

In [84]:
for i in np.nditer(d4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# 7. Reshaping

In the reshaping there are three method..
1. reshape ==> do convert in array formate like 3x4 3rows and 4 columns
2. transpose ==> do convert row into columns and columns into row eg. 3x4 get converted onto 4x3
3. ravel ==> do convert in 1-d array of higher dimensions array like 2-d,3-d etc...

In [85]:
np.transpose(d2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [86]:
d2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [87]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
d4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# 8. Stacking

1. Horizontal Stacking
2. Vertical Stacking

In [89]:
e4=np.arange(12).reshape(3,4)
e5=np.arange(12,24).reshape(3,4)
e5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
np.hstack((e4,e5,e4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [91]:
np.vstack((e4,e5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# 9. Splitting

1. Horizontal splitting ==> it tooks the argument 1st is array and 2nd in how many parts u want to split
2. Vertical splitting ==> it tooks the argument 1st is array and 2nd in how many parts u want to split

In [92]:
np.hsplit(e4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [93]:
np.vsplit(e5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# Numpy array vs Python list

1. Numpy array is more faster than python list
2. Array takes less memory than list

# 10. Broadcasting

1. The term broadcasting describes how Numpy treats arrays with different shapes during arithmetic operation.
2. The smaller array is 'broadcast' accross the larger array so that they have compatible shapes

### Rules of broadcasting

1. Make the two arrays have the same number of dimensions.
> If the number of dimensions of the two arrays are different, add new dimensions with the size 1 to the head of the array with the smaller dimension.
2. Make each dimension of two arrays the same size.
> If the sizes of each dimension of the two arrays do not match, dimensions with size 1 stretched to the size of the other array.
>> If there is a dimension whose size is not 1 in either of the two arrays, it can not be broadcasted and an error is raised.

In [94]:
a=np.arange(12).reshape(4,3)
b=np.arange(3)
print(a+b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [95]:
a,b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([0, 1, 2]))

In [96]:
a=np.arange(12).reshape(3,4)
b=np.arange(3)
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

We got error because of after broadcasting shape is not going to be same for mathematical operation that's why we got the error.(3)==>(1,3)==>(3,3) after broadcasted it would be 3x3 but we have 3x4 that's why error we are getting

In [ ]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a+b)

1 is not presents in anyone shape that can not be increase that's why error I am getting

In [ ]:
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
print(a+b)

# 11. Working with mathematical formulas

1. sigmoid function ==> formula is: 1/(1+np.exp(-x)) ==> sigmoid function returns the value between 0 to 1

In [ ]:
def sigmoid(array):
    return 1/(1+np.exp(-(array)))
a=np.arange(10)
sigmoid(a)

2. Mean squared error

In [ ]:
actual=np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)
actual

In [ ]:
predicted

In [ ]:
def MSE(actual,predicted):
    return np.mean((actual-predicted)**2)
MSE(actual,predicted)

# Working with missing values

In [ ]:
a=np.array([1,2,3,5,np.nan,6])

In [ ]:
a

In [ ]:
np.isnan(a)

In [ ]:
a[np.isnan(a)]

In [ ]:
a[~np.isnan(a)]

# 12. Plotting graphs

Q.1 Plotting a 2-d graph of x=y.  ==> x and y should be shape size of array

In [ ]:
import matplotlib.pyplot as plt
x=np.linspace(-10,10,100)
y=x
plt.plot(x,y)

Q.2 Plotting a graph of y=x^2

In [ ]:
x=np.linspace(-50,50,100)
y=x**2
plt.plot(x,y)

Q.3 Plotting graph of sinx

In [ ]:
x=np.linspace(-20,20,100)
y=np.sin(x)
plt.plot(x,y)

In [ ]:
x=np.linspace(-10,10,100)
y=x*np.log(x)
plt.plot(x,y)

Q.4 Plotting the plot of sigmoid function

In [ ]:
x=np.linspace(-10,10,100)
y=1/(1+np.exp(-x))
plt.plot(x,y)

# 13. Important tips and tricks

#### 13.1 np.sort ==> Returns the sorted copy of an array

In [ ]:
a=np.random.randint(1,100,15)

In [ ]:
a

In [ ]:
np.sort(a)

To sort in descending order use np.sort(a)[::-1]

In [ ]:
np.sort(a)[::-1]

#### 13.2 np.append() ==> appends values along the mention axis at the end of the array

In [ ]:
np.append(a,300)

To add columns or rows in existing 2-d array 

In [ ]:
b=np.arange(12).reshape(3,4)

In [ ]:
b

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

#### 13.3 np.concatenate()==> concatenate a sequence of arrays along an existing axis

In [ ]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
c,d

In [ ]:
np.concatenate((c,d),axis=0)

In [ ]:
np.concatenate((c,d),axis=1)

#### 13.4 np.unique()==> we can get unique values from an array given as a parameter

In [ ]:
e=np.array([1,1,2,2,3,3,4,5,6,6])
f=np.array([[1,2,3,1],[1,2,3,2]])
e,f

In [ ]:
np.unique(e),np.unique(f)

#### 13.5 np.expand_dims()==> With the help of np.expand_dims we can get the expanded dimensions of an array

In [ ]:
a=np.arange(9)

In [ ]:
np.expand_dims(a,axis=1)

In [ ]:
np.expand_dims(a,axis=0)

#### 13.6 np.where()==> Function returns the indices of elements in an input array where the given condition is satisfied

Q.1 Find all the indices with all value greater than 50
Q.2 Replace all value greater than 50 with 0
> In np.where(condition,true's statement,false's statement)

In [ ]:
a=np.random.randint(1,100,15)

In [ ]:
a

In [ ]:
np.where(a>50)

In [ ]:
np.where(a>50,0,a)

#### 13.7 np.argmax(),np.argmin()==>Function returns indices of max/min element of the array in a particular axis

In [ ]:
a

In [ ]:
np.argmax(a)

In [ ]:
np.argmin(a)

#### 13.8 np.cumsum()==>Function is used when we want to compute cumulative sum of array elements over a given  axis

In [ ]:
b=np.arange(12).reshape(3,4)

In [ ]:
b

In [ ]:
a

In [ ]:
np.cumsum(a)

In [ ]:
np.cumsum(b,axis=0)

In [ ]:
np.cumprod(a)

#### 13.9 np.percentile()==>Function compute the nth percentile of the given data(array elements) along the specified axis

In [ ]:
np.percentile(a,75)#1st parameter is array and 2nd is percent

In [ ]:
np.percentile(a,50)

In [ ]:
np.median(a)

#### 13.10 np.histogram()==> Function which represents the frequency of data distribution in the graphical form

In [ ]:
a

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

#### 13.11 np.corrcoef ==> Return pearson product moment correlation coefficient

In [ ]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

#### 13.12 np.isin()==>To check the multiple element in an array

In [97]:
list=[10,20,30,40,50,60,70]
np.isin(a,list)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [98]:
a[np.isin(a,list)]

array([10])

#### 13.13 np.flip()==> Function reverse the order of array elements along the specified axis, preserving the shape of the array

In [100]:
a=np.arange(10)

In [101]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 13.14 np.put()==> Function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array

In [103]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.put(a,[2,3],[30,40])

In [106]:
a

array([ 0,  1, 30, 40,  4,  5,  6,  7,  8,  9])

#### 13.15 np.delete()==> Returns a new array with the deletion of sub-arrays along with the mentioned axis

In [107]:
np.delete(a,0)

array([ 1, 30, 40,  4,  5,  6,  7,  8,  9])

In [108]:
np.delete(a,[3,6,7])

array([ 0,  1, 30,  4,  5,  8,  9])

# Set functions

1. np.union1d
2. np.intersect1d
3. np.setdiff1d
4. np.setxor1d
5. np.in1d

In [109]:
m=np.array([1,2,3,4,5,6])
n=np.array([4,5,6,7,8,9])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.intersect1d(m,n)

array([4, 5, 6])

In [111]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [112]:
np.setxor1d(m,n)

array([1, 2, 3, 7, 8, 9])

In [113]:
np.in1d(m,3)

array([False, False,  True, False, False, False])

In [114]:
m[np.in1d(m,3)]

array([3])

### np.clip()==> Function is used to limit the values in array

In [115]:
a=np.random.randint(1,100,15)

In [116]:
a

array([ 9, 53, 33, 66, 65, 92, 13, 46, 77, 82, 94,  4, 96, 70, 32])

In [117]:
np.clip(a,a_min=20,a_max=80)

array([20, 53, 33, 66, 65, 80, 20, 46, 77, 80, 80, 20, 80, 70, 32])